import { useCallback, useMemo, useState } from "react";

const recommendedVariables = [
  {
    key: "VITE_API_URL",
    label: "HTTP API URL",
    description: "The base URL that the web client uses to reach the backend REST and GraphQL APIs.",
    example: "https://barber-saas-backend-l4iz.onrender.com/api"
  },
  {
    key: "VITE_WS_URL",
    label: "WebSocket URL",
    description: "The endpoint used by the Socket.IO client for live queue/notification updates",
    example: "https://barber-saas-backend-l4iz.onrender.com"
  }
];

const showKeys = new Set(["MODE", "BASE_URL", "DEV", "PROD"]);

export default function EnvPage() {
  const [copyMessage, setCopyMessage] = useState("");

  const visibleEnv = useMemo(() => {
    const entries = [];
    Object.entries(import.meta.env).forEach(([key, value]) => {
      if (key.startsWith("VITE_") || showKeys.has(key)) {
        entries.push({ key, value });
      }
    });

    recommendedVariables.forEach(item => {
      if (!entries.find(entry => entry.key === item.key)) {
        entries.push({ key: item.key, value: undefined });
      }
    });

    return entries.sort((a, b) => a.key.localeCompare(b.key));
  }, []);

  const snippet = useMemo(() => {
    return recommendedVariables
      .map(item => `${item.key}=${import.meta.env[item.key] || item.example}`)
      .join("\n");
  }, []);

  const handleCopySnippet = useCallback(async () => {
    if (!navigator?.clipboard) {
      setCopyMessage("Clipboard not available");
      return;
    }
    try {
      await navigator.clipboard.writeText(`# Copy to .env.local\n${snippet}`);
      setCopyMessage("Copied! Paste into .env.local");
      setTimeout(() => setCopyMessage(""), 2500);
    // eslint-disable-next-line no-unused-vars
    } catch (error) {
      setCopyMessage("Unable to copy");
    }
  }, [snippet]);

  return (
    <div className="min-h-screen bg-slate-50 py-8">
      <div className="max-w-5xl mx-auto space-y-6 px-4">
        <div className="bg-white rounded-3xl shadow-2xl border border-gray-100 p-8 space-y-4">
          <h1 className="text-3xl font-black text-gray-900">.env / Environment</h1>
          <p className="text-gray-600">
            The values below reflect what Vite exposes to the client build. Copy the snippet into a <span className="font-mono text-sm">.env.local</span> file at the project root, then restart the dev server for changes to take effect.
          </p>
          <p className="text-sm text-gray-500">
            We encourage sourcing the URLs from environment variables so you can target staging, QA, or preview deployments without a code change.
          </p>
        </div>

        <div className="grid gap-5 md:grid-cols-2">
          {recommendedVariables.map(item => {
            const value = import.meta.env[item.key];
            return (
              <div key={item.key} className="bg-white rounded-3xl border border-gray-100 shadow-sm p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-bold uppercase tracking-widest text-gray-500">{item.label}</p>
                    <p className="text-xs text-gray-400">{item.key}</p>
                  </div>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${value ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>
                    {value ? "Configured" : "Default"}
                  </span>
                </div>
                <p className="text-sm text-gray-700 min-h-[3rem]">{item.description}</p>
                <div className="text-sm font-mono text-slate-600 bg-slate-50 rounded-xl px-3 py-2 border border-dashed border-slate-200">
                  {value || item.example}
                </div>
              </div>
            );
          })}
        </div>

        <div className="bg-white rounded-3xl shadow-2xl border border-gray-100 p-6 space-y-3">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-xl font-bold text-gray-900">Sample .env.local</h2>
              <p className="text-sm text-gray-500">Paste this into <span className="font-mono">.env.local</span> or edit <span className="font-mono">.env</span> for build-time values.</p>
            </div>
            <button
              onClick={handleCopySnippet}
              className="px-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold rounded-2xl text-sm shadow-lg shadow-indigo-100 hover:opacity-90 transition-all"
            >
              {copyMessage || "Copy snippet"}
            </button>
          </div>
          <pre className="bg-slate-950 text-xs text-white rounded-2xl p-4 font-mono overflow-x-auto">
{`# Auto-generated by the platform view\n${snippet}`}
          </pre>
          <p className="text-xs text-gray-500">Restart the Vite dev server after editing the file so the CLI picks up the new values.</p>
        </div>

        <div className="bg-white rounded-3xl border border-gray-100 shadow-lg">
          <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
            <div>
              <h3 className="text-lg font-semibold text-gray-900">Exposed environment variables</h3>
              <p className="text-sm text-gray-500">These are the keys currently available via <span className="font-mono">import.meta.env</span>.</p>
            </div>
          </div>
          <div className="divide-y divide-gray-100">
            {visibleEnv.length === 0 && (
              <div className="p-6 text-sm text-gray-500">No custom variables have been defined yet.</div>
            )}
            {visibleEnv.map(entry => (
              <div key={entry.key} className="px-6 py-4 flex flex-col md:flex-row md:items-center md:justify-between gap-2">
                <div>
                  <p className="text-sm font-semibold text-gray-800 break-all">{entry.key}</p>
                  <p className="text-xs text-gray-400">{entry.key === "MODE" ? "Build mode" : ""}</p>
                </div>
                <div className="text-sm font-mono text-slate-600 break-all">
                  {entry.value ?? "(not set)"}
                </div>
              </div>
            ))}
          </div>
          <div className="px-6 py-4 text-xs text-gray-500 border-t border-gray-100">
            Environment variables are baked into the build. Changing values requires restarting the dev server or rebuilding the project for production deployments.
          </div>
        </div>
      </div>
    </div>
  );
}